### ISSUE TITLE
Implement SKV Partial Update

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#44] opened 2020-09-21 20:08 UTC
A partial update is when the user only wants to write a subset of the fields of a record. We want to optimize for this case with a new partialUpdate RPC and interface, which will reduce traffic over the network.

- Implement a new DTO and RPC for partialUpdate based on the SKV write RPC.
- Implement the RPC in the 3SI Module. For this task we do not need to store delta records on the server, the server can copy and create full records. We can have a separate task for storing delta records.
- Implement the interface in https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/module/k23si/client/k23si_client.h The interface should have two overloaded functions, one for specifying fields by  name and one by index: "seastar::future\<WriteResult\> partialUpdate(T& record, std::vector<k2::String> fieldsToUpdate" and "seastar::future\<WriteResult\> partialUpdate(T& record, std::vector<uint32_t> fieldsToUpdate"
- A more complicated part of this task is dealing with schema versioning. See the design here: https://github.com/futurewei-cloud/chogori-platform/blob/master/docs/RFC/schema_versioning.md#partial-updates
- Add tests, including tests for the schema versioning cases mentioned above, here: https://github.com/futurewei-cloud/chogori-platform/blob/master/test/k23si/SKVClientTest.cpp
- Modify the TPC-C test to use partial updates. If you have trouble running TPC-C for testing let me know and I can help or take over this part of the task. https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/cmd/tpcc/transactions.h

**Comment by YazhiFeng** [comment] 2020-09-22 13:50
Hi, Justin. I got some questions about implementing partialUpdate. 

1. When I implement the interface in k23si_client.h, considering a user app sending partialUpdate requests through the k23_client, the most common way to call this partialUpdate interface I think is : The user declares a SKVRecord and enters updated fields using serializeNext, skips non-updated fields using skipNext, and then calls the interface with txnHandle.partialUpdate <>(record) from k23si_client. Should I implement interface in this scenario?

So I don't know under what circumstances this kind of interface "partialUpdate(T& record, std::vector<> fieldsToUpdate)" is called. Should every fields in the record be serialized? 

2. I want to confirm that does partialUpdate use SKVRecord::Storage to send value to server as K23SIWriteRequest does.  But it can reduce network traffic through less fieldData. 

3. Is the partialUpdate relative to the latest record? It means that I can supplement the non-updated fields with the fields from the latest committed record.

**Comment by jfunston** [comment] 2020-09-22 17:42
1.  You are correct on how the user will use SKVRecord but the problem is that the fields are optional, and by using only skipNext we don't know if the user wants to do a partial update to set a field to Null or if they do not want to set the field. So we need some extra information from the user.
2. Yes, correct.
3. Yes, correct.

**Comment by jfunston** [comment] 2020-09-22 21:58
I made some tweaks to TPC-C and the run script so it should be easier to run TPC-C with all of the components locally. It is not suitable for performance benchmarking but it will work for functional tests. The script is test/integration/test_k23si_tpcc.sh

**Comment by jfunston** [comment] 2020-09-23 18:41
Hi Yazhi, please configure your editor to use spaces instead of tabs, which will be consistent with the rest of the project.

**Comment by YazhiFeng** [comment] 2020-09-28 12:35
Hi, Justin. I want to track my progress with you. Here I also have some questions.

First, the partialUpdate functionalities development has been basically completed. Including: 

1. Implement a new DTO and RPC for partialUpdate; 
2. Implement the interface in k23si_client;
3. Implement the RPC in the 3SI Module. PartialUpdate for both the same version and different versions of a schema can be done. 
4. Now I am doing test cases in SKVClientTest.

Second, I'd like to have some design discussions with you: 

1. For a partialUpdate whose previous WI (same key) is within the same transaction, we compare and fill in the missing fields based on its own WI; 
For a partialUpdate who faces Push with another transaction, if it wins Push, we compare and fill in the missing fields based on the previous committed SKVRecord.
2. At present, the semantics for a NULL fieldsToUpdate parameter in k23si_client partialUpdate<>() is that we do partial update according to the semantics of Record's excludedFields. 0s fields in excludedFields indicate they need to be updated.
3. For a field that indicated update in the fieldsToUpdate parameter, but it has been skipNext()  when the record is created. If the field type is string,  we use NULL string to fill in. If the field type is uint32 or uint64, we return Error for now. The other option is to fill in with zero.
4. The private member _failed in class K2TxnHandle turns to TRUE when checkResponseStatus meet some kinds of returns. After _failed turns to true, this Txn can not implement reads/writes/partialUpdates any more. But some returns can be caused by an error parameter from the user, in this situation, the user might correct and continue do more writes. So I think here has to be modified for a convenient use. 

Third, I think there is a bug in handleWrite function in Class K23SIPartitionModule. The situation is when a transaction writes the same key multiple times, the new WI is inserted without clearing the previous WI. I made some modification below whose logic can also be applied to partialUpdate.

```
K23SIPartitionModule::handleWrite {
    ... ...

>    // Clean up if req and WI are the same transaction
>    if (versions.size() > 0 && versions[0].status == dto::DataRecord::WriteIntent && request.mtr == versions[0].txnId.mtr) {
>        _queueWICleanup(std::move(versions[0]));
>        versions.pop_front();
>    }

    // all checks passed - we're ready to place this WI as the latest version(at head of versions deque)
    return _createWI(std::move(request), versions, deadline).then([this]() mutable {
        K2DEBUG("Partition: " << _partition << ", WI created");
        return RPCResponse(dto::K23SIStatus::Created("wi created"), dto::K23SIWriteResponse{});
    });
} // end handleWrite 
```

**Comment by jfunston** [comment] 2020-09-28 20:26
Great, thanks for the update. For your questions:

1. Yes, both of those situations make sense to me.
2. I am not sure what you mean here. Do you have a branch on github where I can look at the code?
3. If a field is designated NULL by the user calling skipNext() then you do not need to write anything to the fieldData payload. So you do not need to write an empty string for a string type field or a 0 for an integer type field. It will work the same way as a normal full record write. This is because the excludedFields variable is stored on the server as part of SKVRecord::Storage so the server can interpret the fieldData payload correctly.
4. Perhaps. Do you have a list of these error cases where the user can fix it without aborting the transaction?

For the last point, yes that is a bug and it would be great if you can fix it. The problem is that only one WriteIntent will be cleaned up at finalization time. I think it is OK to have multiple WriteIntents on the same key for the same in progress transaction. Your solution might have some tricky consistency issues though because _createWI can fail because it has a remote persistence call. I think it is better to fix the finalization handling so that it can handle multiple WriteIntents on the same key.

**Closed** 2020-10-13 18:30 UTC
Labels: skv
