### ISSUE TITLE
3SI Transaction test cases scenario 02

### ISSUE THREAD

**Issue by jfunston** [futurewei-cloud/chogori-platform#38] opened 2020-09-03 23:49 UTC
Implement scenario 02 test cases from https://github.com/futurewei-cloud/chogori-platform/blob/master/docs/RFC/K23SI_testing.md

You will need to implement the functionality to delay finalization. You can do this with an option in the txn END request similar to the existing syncFinalize option. The delay itself would go here: https://github.com/futurewei-cloud/chogori-platform/blob/master/src/k2/module/k23si/TxnManager.cpp#L344

You may also need to increase the heartbeat deadline config option for the tests.

Also consider other test cases that could be added to this scenario, especially requests against the keys that have the WI and aborted records.

**Comment by YazhiFeng** [comment] 2020-09-07 13:36
1. Should I implement to delay finalization through modifying _end() Function to sleep 10s for the asyncFinalize mode, at the mean time  set the END request parameter to K23SITxnEndRequest::syncFinalize = false ? 

```
rec.bgTaskFut = rec.bgTaskFut
      .then([] {
>>          return **seastar::sleep(0us);**    // modify to  'seastar::sleep(10s);' 
      })
      .then([this, &rec]() {
      // TODO Deadline based on transaction size
          auto timeout = (10s + _config.writeTimeout() * rec.writeKeys.size())/_config.finalizeBatchSize();
          return _finalizeTransaction(rec, FastDeadline(timeout));
      });
```

2. Is the heartbeat deadline configured while Collection was creating by setting the CollectionCreateRequest::metadata.heartbeatDeadline for example  to 5 seconds ?

**Comment by jfunston** [comment] 2020-09-07 17:19
1. You can create a new END request parameter for how long to sleep at that point. Yes, you can have K23SITxnEndRequest::syncFinalize = false

2. Yes, that is how to set the heartbeat deadline.

**Comment by YazhiFeng** [comment] 2020-09-10 13:52
I have the following two questions:

1. When I create a second collection (different collection name) in the cluster, I can get a S201_CREATE response, and then the new collection can be achieved by CPO_COLLECTION_GET rpc and returns a S200_OK response. But the partition->astate of the new collection is **pending_assignment**, which will refuse the read/write requests. I could not figure out the cause of this mistake.  Some information is listed below. 

question 1 info printer：
```
3SITxnTest.cpp:1334 @operator()]SC02. status: 200 with MESG: collection found
3SITxnTest.cpp:1335 @operator()]sc02 collection name|hashScheme|retention|heartbeat: 
SC02_3si_txn_collection | Hash-CRC32C | 0000:05:00:00.000.000 | 0000:00:00:00.100.000
------- Partition Info printer for k1({pkey=SC02_pkey1, rkey=}) -------
pvid(id|rangeVersion|assignmentVersion): 211
startKey(12297829382473034410) endKey(18446744073709551615) astate(pending_assignment).
preferEP: tcp+k2rpc://0.0.0.0:10002  EP set size: 1  endpoints: tcp+k2rpc://0.0.0.0:10002; 
[ERROR] 3SITxnTest.cpp:1382 @operator()]status1 == Statuses::S201_Created
[ERROR] 3SITxnTest.cpp:1382 @operator()]+++++++++++++++++++++ Expectation failed ++++++++++++++++( actual=[410 Gone]: collection refresh needed in write, exp=[201 Created]: )

``` 

Collection Parameters:
```
auto request = dto::CollectionCreateRequest{
            .metadata{
                .name = sc02_cname,
                .hashScheme = dto::HashScheme::HashCRC32C,
                .storageDriver = dto::StorageDriver::K23SI,
                .capacity{
                    .dataCapacityMegaBytes = 10,
                    .readIOPs = 1000,
                    .writeIOPs = 1000
                },
                .retentionPeriod = 5h,
>>                .heartbeatDeadline = 30000ms,     // question 2 here
            },
            .clusterEndpoints = _k2ConfigEps(),
            .rangeEnds{}
        };
```

2. As listed above, I set the heartbeatDeadline of the collection by setting CollectionCreateRequest.metadata.heartbeatDeadline . But as the printer shows the heartbeat is still 100ms which did not change . How can I do it right?

**Comment by jfunston** [comment] 2020-09-10 22:43
1. I believe the problem here is that a storage node can have only one collection assigned to it. You need to either use the same collection for all of the tests, or split the tests into separate instances (meaning run the other tests with a different integration test script). There is a bug in the CPO though, it should be showing "failed_assignment" instead of "pending_assignment". Can you look into fixing this as part of the PR? You should be able to find the bug in CPOService.cpp

2. Sorry this is because I answered your previous question wrong. The heartbeat deadline is determined by a CPO command line parameter, not the create collection request. You need to pass "--heartbeat_deadline=30s" to the CPO on the command line.

**Comment by YazhiFeng** [comment] 2020-09-11 07:55
Thanks for the help. The questions are solved. Please check the PR.

I also add four test cases to test the Async_END as listed below. These cases are implemented in Scenario-02, cases 11-14. 

| test case                                                    | Expected result            | Possible fix needed |
| ------------------------------------------------------------ | -------------------------- | ------------------- |
| TXN with a WRITE and then END asynchronously with Commit. Finalize with abort for the same key at time interval. | Cannot abort committed txn |                     |
| TXN with a WRITE and then END asynchronously with Abort. Finalize with commit for the same key at time interval. | Cannot commit missing key  |                     |
| TXN with a WRITE and then END asynchronously with Commit. Validate with a read for the async end key. | OK                         |                     |
| TXN with a WRITE and then END asynchronously with Abort. Validate with a read for the async end key. | NotFound/Old data          |                     |

**Comment by YazhiFeng** [comment] 2020-09-11 08:05
Scenarios 03-08 do not list the test cases, I want to ask how will the next scenarios be tested.

**Comment by jfunston** [comment] 2020-09-16 01:32
You can skip scenario 03 for now since we don't have a way to test the interval range portion of it, so you can move on to scenario 04 next. Can you come up with the test cases on your own for scenario 04. I made a new issue for it: https://github.com/futurewei-cloud/chogori-platform/issues/40

**Closed** 2020-09-16 18:01 UTC
Labels: k23si
